### ISSUE TITLE
Files Missing in Build/

### ISSUE THREAD

**Issue by Dead-Bytes** [microsoft/BitNet#31]
```bash
Traceback (most recent call last):
  File "/home/deadbytes/Documents/BitNet/setup_env.py", line 202, in <module>
    main()
  File "/home/deadbytes/Documents/BitNet/setup_env.py", line 180, in main
    prepare_model()
  File "/home/deadbytes/Documents/BitNet/setup_env.py", line 106, in prepare_model
    run_command(["./build/bin/llama-quantize", f32_model, i2s_model, "I2_S", "1"], log_step="quantize_to_i2s")
  File "/home/deadbytes/Documents/BitNet/setup_env.py", line 63, in run_command
    subprocess.run(command, shell=shell, check=True, stdout=f, stderr=f)
  File "/home/deadbytes/miniconda3/envs/bitnet-cpp/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/deadbytes/miniconda3/envs/bitnet-cpp/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/deadbytes/miniconda3/envs/bitnet-cpp/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './build/bin/llama-quantize'
```

Facing this error anyone else got the smae?

**Comment by Dead-Bytes** [comment]
fixed
