### ISSUE TITLE
Fail to run eval_ppl and eval_task

### ISSUE THREAD

**Issue by Kimho666** [microsoft/BitNet#96]
HF_ENDPOINT=https://hf-mirror.com python eval_task.py --tasks piqa
I1030 09:44:56.959918 3586089 utils.py:145] Note: detected 80 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
I1030 09:44:56.960034 3586089 utils.py:148] Note: NumExpr detected 80 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
I1030 09:44:56.960092 3586089 utils.py:161] NumExpr defaulting to 16 threads.
I1030 09:44:57.604907 3586089 config.py:54] PyTorch version 2.2.2+cpu available.
Traceback (most recent call last):
  File "/share/lijinhao/soft_link/root/research/quantization/BitNet/models/bitnet_b1_58-3B/eval_task.py", line 65, in <module>
    main(args)
  File "/share/lijinhao/soft_link/root/research/quantization/BitNet/models/bitnet_b1_58-3B/eval_task.py", line 28, in main
    model = BitnetForCausalLM.from_pretrained(
  File "/share/lijinhao/anaconda3/envs/bitnet-cpp1/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3974, in from_pretrained
    resolved_archive_file, sharded_metadata = get_checkpoint_shard_files(
  File "/share/lijinhao/anaconda3/envs/bitnet-cpp1/lib/python3.9/site-packages/transformers/utils/hub.py", line 1075, in get_checkpoint_shard_files
    index = json.loads(f.read())
  File "/share/lijinhao/anaconda3/envs/bitnet-cpp1/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte

**Comment by potassiummmm** [comment]
Thanks for reporting. These files are provided by the Hugging Face model, they are not part of our work, you can raise an issue with the original repository.

**Comment by Kimho666** [comment]
请问，跑evaluation得需要gpu的torch环境吧，我装的时候都是cpu的torch环境。所以我应该是需要两个conda虚拟环境？
